//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec 14 2017 14:12:44).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BDUser : NSObject
{
    NSString *_userName;
    NSString *_displayName;
    NSString *_bduss;
    NSString *_userId;
    NSString *_stoken;
    NSString *_avatarUrl;
    NSString *_oauthType;
    NSString *_oauthAvatarUrl;
    NSString *_nickName;
    NSString *_userUK;
    NSString *_userSignKeyInfo;
}

+ (id)profileValueForKey:(id)arg1 expectedType:(Class)arg2;
+ (id)profileValueForKey:(id)arg1;
+ (void)setProfileInfo:(id)arg1 forKey:(id)arg2;
+ (void)transferOldVersionUserDefaultsForUserId:(id)arg1;
+ (void)clearOldVersionUserDefaultsData;
+ (void)cleanupOldVersionCacheData;
+ (id)userWithOldVersionCachedData;
+ (id)showUserName;
+ (id)userCardCatalogStoken;
+ (id)userSafeBoxStoken;
+ (id)userCachePath;
+ (_Bool)isCloudDownItemFinish;
+ (void)updateCloudDownFinishStatus:(_Bool)arg1;
+ (id)getMyDisplayName;
+ (id)userSignKey;
+ (void)setUserSignKey:(id)arg1;
+ (void)updateUserSignKey:(id)arg1;
+ (void)setUserIsAutoUpgradeToSVIP:(_Bool)arg1;
+ (_Bool)isAutoUpgradeToSVIP;
+ (double)exSVIPExpireTime;
+ (void)setExUserSVIPExpireTime:(double)arg1;
+ (double)exVipExpireTime;
+ (void)setExUserVipExpireTime:(double)arg1;
+ (double)svipExpireTime;
+ (void)setUserSVIPExpireTime:(double)arg1;
+ (double)vipExpireTime;
+ (void)setUserVipExpireTime:(double)arg1;
+ (void)setExperienceVIP:(_Bool)arg1;
+ (_Bool)isExperienceVIP;
+ (long long)userIdentity;
+ (void)setUserIsSVIP:(_Bool)arg1;
+ (_Bool)isSVIP;
+ (void)setUserIsVIP:(_Bool)arg1;
+ (_Bool)isVIP;
+ (_Bool)isExSVIP;
+ (_Bool)isExVIP;
+ (int)accountBindType;
+ (void)prepareAccountBindType:(int)arg1 BDUserName:(id)arg2;
+ (id)userFormOldVersionKeyChain;
+ (void)setUserUK:(id)arg1;
+ (id)userUK;
+ (void)setAvatarUrl:(id)arg1;
+ (id)avatarUrl;
+ (void)setNickName:(id)arg1;
+ (id)nickName;
+ (long long)sex;
+ (void)logout;
+ (double)loginTime;
+ (id)sourceUserName;
+ (void)setUserUname:(id)arg1;
+ (id)userUname;
+ (long long)sourceType;
+ (id)headUrl;
+ (id)sourceUserId;
+ (id)userId;
+ (id)stoken;
+ (id)bduss;
+ (id)userName;
+ (_Bool)isActive;
+ (_Bool)isLogin;
+ (id)currentUser;
@property(copy) NSString *userSignKeyInfo; // @synthesize userSignKeyInfo=_userSignKeyInfo;
@property(copy, nonatomic) NSString *userUK; // @synthesize userUK=_userUK;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(copy, nonatomic) NSString *oauthAvatarUrl; // @synthesize oauthAvatarUrl=_oauthAvatarUrl;
@property(copy, nonatomic) NSString *oauthType; // @synthesize oauthType=_oauthType;
@property(copy, nonatomic) NSString *avatarUrl; // @synthesize avatarUrl=_avatarUrl;
@property(copy, nonatomic) NSString *stoken; // @synthesize stoken=_stoken;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSString *bduss; // @synthesize bduss=_bduss;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;

- (double)loginTime;
- (void)updateLoginTime;
- (id)initWithLoginModel:(id)arg1;
- (_Bool)isOldVersionObject;
- (void)markAsOldVersionObject:(_Bool)arg1;
@property(nonatomic) _Bool isAntiStealingUser;

@end

