//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Dec 14 2017 14:12:44).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class VipSubscriptionGuideViewController;

@interface VIPExpirationManage : NSObject
{
    _Bool _videoBackup;
    _Bool _livePhotoBackup;
    _Bool _alertShowing;
    long long _requestTag;
    VipSubscriptionGuideViewController *_guideViewController;
}

+ (id)verifyRedirectUrl:(id)arg1;
+ (id)sharedVIPExpirationManage;
@property(retain, nonatomic) VipSubscriptionGuideViewController *guideViewController; // @synthesize guideViewController=_guideViewController;
@property(nonatomic) long long requestTag; // @synthesize requestTag=_requestTag;
@property(nonatomic) _Bool alertShowing; // @synthesize alertShowing=_alertShowing;
@property(nonatomic) _Bool livePhotoBackup; // @synthesize livePhotoBackup=_livePhotoBackup;
@property(nonatomic) _Bool videoBackup; // @synthesize videoBackup=_videoBackup;

- (id)getResidentMsg;
- (void)cleanQuotaMsgWith:(id)arg1 endTime:(id)arg2;
- (id)getQuotaMsg;
- (void)cleanVipExpireAllNotice;
- (void)getVipExpireNotice;
- (void)setVipExpireNoticeInvalidMsgId:(id)arg1;
- (void)handelVipExpireTimeChangedNotice:(id)arg1;
- (void)handleUserLogOutNotification:(id)arg1;
- (void)handleUserLoginNotification:(id)arg1;

- (_Bool)shouldShowExpirationView;
- (_Bool)verifyTimeWithUserVipInfo:(id)arg1;
- (void)handleUserVipExpireNoticeRequestModel:(id)arg1;
- (_Bool)date:(id)arg1 isBetweenDate:(id)arg2 andDate:(id)arg3;
- (id)date;
- (void)showExpirationViewWithTitle:(id)arg1 productType:(long long)arg2;
- (void)handleApplicationWillLaunchedNotification:(id)arg1;
- (void)handleVIPChangeNotification:(id)arg1;
- (void)handleVIPExpirationWithWebProductType:(long long)arg1;
- (void)handleVIPExpirationNotification:(id)arg1;
- (void)handleSVIPExpirationNotification:(id)arg1;
- (void)handleAppBecomeActiveNotification:(id)arg1;
- (void)checkVIPExpiration;
- (void)dealloc;
- (id)init;

@end

